easy_admin:
    site_name: Studio Agate

    list:
        max_results: 50

    design:
        brand_color: 'rgb(88, 88, 216)'

        templates:
            layout: easy_admin/layout.html.twig

        form_theme:
            - 'form/easyadmin_form_theme.html.twig'

        menu:
            - { label: 'admin.links.admin_home', route: 'easyadmin', default: true, icon: 'home' }
            - { label: 'admin.links.back_to_site', route: 'agate_portal_home', icon: 'arrow-left' }

            - { label: 'admin.menu.site' }
            - { label: 'admin.links.config', route: 'admin_config', icon: 'cogs', permission: ROLE_ADMIN }
            - { entity: 'PortalElement', icon: 'file-text-o', permission: ROLE_ADMIN }
            - { entity: 'Pages', icon: 'file-code-o', permission: CAN_EDIT_CMS }
            - { entity: 'Product', icon: 'box-open', permission: CAN_EDIT_PRODUCTS }
            - { entity: 'ProductFile', icon: 'box-open', permission: CAN_EDIT_PRODUCTS }
            - { entity: 'ProductCategory', icon: 'boxes', permission: CAN_EDIT_PRODUCTS }

            - { label: 'admin.menu.users', permission: ROLE_ADMIN }
            - { entity: 'Users', icon: 'users', permission: ROLE_ADMIN }
            - { entity: 'Subscriptions', icon: 'address-card', permission: ROLE_ADMIN }

            - { label: 'admin.menu.esterenmaps', permission: ROLE_ADMIN }
            - { entity: 'Maps', icon: 'map', permission: ROLE_ADMIN }
            - { entity: 'Factions', icon: 'flag', permission: ROLE_ADMIN }

            -   label: 'admin.menu.esterenmaps_data'
                permission: ROLE_ADMIN
                children:
                    - { entity: 'Markers', permission: ROLE_ADMIN }
                    - { entity: 'Routes', permission: ROLE_ADMIN }
                    - { entity: 'Zones', permission: ROLE_ADMIN }

            -   label: 'admin.menu.types'
                permission: ROLE_ADMIN
                children:
                    - { entity: 'MarkersTypes', permission: ROLE_ADMIN }
                    - { entity: 'RoutesTypes', permission: ROLE_ADMIN }
                    - { entity: 'ZonesTypes', permission: ROLE_ADMIN }
                    - { entity: 'TransportTypes', permission: ROLE_ADMIN }
