doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                server_version: 5.7
                url: '%env(DATABASE_URL)%'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            EsterenMaps:
                type: annotation
                dir: '%kernel.project_dir%/src/EsterenMaps/Entity/'
                is_bundle: false
                prefix: EsterenMaps\Entity
                alias: EsterenMaps
            User:
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity/'
                is_bundle: false
                prefix: User\Entity
                alias: User
