easy_admin:
    entities:
        MarkersTypes:
            label: admin.maps.markers_types
            class: EsterenMaps\Entity\MarkerType
            controller: Admin\CustomController\EsterenMaps\AdminMarkerTypeController
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - { property: webIcon, type: image, virtual: false }
                    - markers
            form:
                fields:
                    - property: translatedNames
                      label: 'admin.entities.common.name'
                      type: Main\Form\TranslatableStringType
                    - property: translatedDescriptions
                      label: 'admin.entities.common.description'
                      type: Main\Form\TranslatableStringType
                    - property: iconFile
                      type: file
            edit:
                fields:
                    - property: iconFile
                      type: file
                      type_options:
                          required: false
                          help: 'admin.entities.marker_type.icon_override_help'
                    - iconWidth
                    - iconHeight
                    - iconCenterX
                    - iconCenterY
