# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    container.dumper.inline_class_loader: true
    container.autowiring.strict_mode: true

    version_code: '%env(RELEASE_VERSION)%'
    version_date: '%env(RELEASE_DATE)%'
    locale: fr
    locales:
        fr: fr
        en: en
    locales_regex: 'fr|en'

    esterenmaps.tile_size: 168
    esterenmaps.output_directory: '%kernel.project_dir%/public/maps_tiles/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $defaultLocale:            '%locale%'
            array $locales:                   '%locales%'
            string $imageMagickPath:          '%env(resolve:IMAGEMAGICK_PATH)%'
            string $outputDirectory:          '%esterenmaps.output_directory%'
            string $projectDir:               '%kernel.project_dir%'
            string $publicDir:                '%kernel.project_dir%/public'
            int $tileSize:                    '%esterenmaps.tile_size%'
            Gedmo\Translatable\Entity\Repository\TranslationRepository $translationRepository: '@Gedmo\Translatable\Entity\Repository\TranslationRepository'
    _instanceof:
        Main\DependencyInjection\PublicService:
            public: true

    Admin\:
        resource: '../src/Admin/*'
        exclude: '../src/Admin/{DTO,DependencyInjection}'

    EsterenMaps\:
        resource: '../src/EsterenMaps/*'
        exclude: '../src/EsterenMaps/{Constraints,Entity,DTO,ImageManagement,Mode}'

    Main\:
        resource: '../src/Main/*'
        exclude: '../src/Main/{Entity,DTO}'

    User\:
        resource: '../src/User/*'
        exclude: '../src/User/{Entity,Model,Security/Exception}'

    Gedmo\Translatable\Entity\Repository\TranslationRepository:
        factory: ['@doctrine', 'getRepository']
        arguments: ['Gedmo\Translatable\Entity\Translation']
